### ISSUE TITLE
Suggestion: Making SMD resistor area bigger

### ISSUE THREAD

**Issue by Ardakilic** [Refuhr/2dsxlusbc#1]
Hello, appreciate the effort for the PCB, kudos!

I have a simple request, I hope this is considered.

0402 SMD soldering by hand is too hard, so I'd appreciate if this resistor would be changed with a bigger one such as 0805 or at least 0603. I believe there's enough space for the bigger resistor on the board. I will possibly fail and make a jumper wire to the connector, or grind the trace for bigger area to solder.

Thanks once again for making this available for us all!

Have a great day!

**Comment by Refuhr** [comment]
I now have added two additional versions with 0603 and 0805 resistors in [design files](https://github.com/Refuhr/2dsxlusbc/tree/main/design%20files).

**Comment by Ardakilic** [comment]
Hello @Refuhr , awesome! Thanks for these! I'll definitely check these out!

I'll possibly print all the variations from JLCPCB and check out. Also, if you upload to OSHPark, please let me know.

**Comment by Refuhr** [comment]
Firstly, thank you for your suggestion this was a good idea! I put all the oshpark links into README.md and added a 1206 version. If you test the different PCBs, please leave some feedback in the comments.

**Comment by Ardakilic** [comment]
Just a heads-up, I ordered bigger variants a couple of days ago. I already received the USB-c connectors. I have a broken new 2ds xl board, first I'll try on that and I'll let you know the situation, but due to slow shipping it may take a while.

**Comment by Ardakilic** [comment]
Hello @Refuhr , apologies for too late post. I can confirm 0603 can be used perfectly! 🎉

**Comment by Refuhr** [comment]
Glad it worked, also apologies for the late reply. :)
