### ISSUE TITLE
0805 non-Qi version works perfectly on 2ds ll

### ISSUE THREAD

**Issue by Aetf** [Refuhr/2dsxlusbc#4]
Hi, just wanted to say thank you for the PCB design, and to provide feedback that the 0805 non-Qi version works perfectly on my 2DS LL.

I used a cheap hotplate (this [one](https://www.aliexpress.us/item/3256805414817280.html?spm=a2g0o.order_list.order_list_main.4.21ef1802uJ76Wy&gatewayAdapt=glo2usa)) to solder the USB C connector and 2 resistors. It's my first time doing this but it worked out really well!

![PXL_20230826_070313425 MP](https://github.com/Refuhr/2dsxlusbc/assets/1519759/825a82ee-4e46-466b-a2d1-67e8d9e42b29)

I do have to grind the battery bracket quite a bit to make it fit.

End result:

![PXL_20230828_020317386 MP](https://github.com/Refuhr/2dsxlusbc/assets/1519759/8fdef556-9422-4204-88c7-fe456b464859)

**Comment by Refuhr** [comment]
Good job! I forgot to take a picture of the battery bracket before I assembled it and I was to lazy to open it back up just to take that picture. :)
